# Define common settings here to avoid repeating them
x-common-variables: &common-variables
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: Server=sqlserver;Database=OrderDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True
  RabbitMQ__Host: rabbitmq
  Razorpay__KeyId: rzp_test_*************
  Razorpay__KeySecret: yi***************

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    ports: ["5672:5672", "15672:15672"]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
    volumes: ["rabbitmq_data:/var/lib/rabbitmq"]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sql
    ports: ["1433:1433"]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
    healthcheck:
      test: ["CMD", "/usr/bin/timeout", "5", "/bin/bash", "-c", "</dev/tcp/localhost/1433"]
    volumes: ["sqlserver_data:/var/opt/mssql"]

  order-service:
    build:
      context: .
      dockerfile: Order.Service/Dockerfile
    container_name: order-service
    ports: ["5170:5170"]
    environment:
      <<: *common-variables  # Injects all the settings once
    depends_on:
      rabbitmq: { condition: service_healthy }
      sqlserver: { condition: service_healthy }

  payment-service:
    build:
      context: .
      dockerfile: Payment.Service/Dockerfile
    container_name: payment-service
    ports: ["5030:8080"]
    environment:
      <<: *common-variables  # Injects the same settings here
    depends_on:
      rabbitmq: { condition: service_healthy }
      sqlserver: { condition: service_healthy }

volumes:
  rabbitmq_data:
  sqlserver_data: